import { existsSync, readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

describe("report export UI smoke contract", () => {
  it("exercises the real report export menu before checking Supabase artifacts", () => {
    const packageJson = JSON.parse(readFileSync("package.json", "utf8"));
    const sourcePath = "scripts/smoke-report-export-ui.ts";

    expect(packageJson.scripts["smoke:report-export-ui"]).toBe(
      "node --experimental-strip-types scripts/smoke-report-export-ui.ts",
    );
    expect(packageJson.scripts["smoke:critical"]).not.toContain("smoke:report-export-ui");
    expect(packageJson.scripts["smoke:release"]).toContain("smoke:report-export-ui");
    expect(existsSync(sourcePath)).toBe(true);

    const source = readFileSync(sourcePath, "utf8");
    const sharedReportSource = readFileSync(
      "src/lib/reporting/shared-report-data.ts",
      "utf8",
    );

    expect(source).toContain("runContentReportManualSourceSmoke");
    expect(source).toContain("REPORT_SMOKE_CREATOR_DISPLAY_NAME");
    expect(source).toContain('process.env.SMOKE_CREATOR_DISPLAY_NAME = REPORT_SMOKE_CREATOR_DISPLAY_NAME');
    expect(source).toContain("Mina Park");
    expect(source).not.toContain('"Dev Creator"');
    expect(source).toContain("HTML report");
    expect(source).toContain("report-builder");
    expect(source).toContain("report-builder-layout");
    expect(source).toContain("report-builder-control-panel");
    expect(source).toContain("report-builder-preview-panel");
    expect(source).toContain("report-builder-template-strip");
    expect(source).toContain("report-builder-reader-promise");
    expect(source).toContain("report-builder-reader-promise-item");
    expect(source).toContain("data-promise-item");
    expect(source).toContain("report-builder-story-strip");
    expect(source).toContain("report-builder-story-step");
    expect(source).toContain("report-builder-decision-recipe");
    expect(source).toContain("report-builder-decision-recipe-item");
    expect(source).toContain("data-recipe-step");
    expect(source).toContain("report-builder-export-contract");
    expect(source).toContain("report-builder-contract-item");
    expect(source).toContain("data-contract-item");
    expect(source).toContain("lead-metric");
    expect(source).toContain("trust-gate");
    expect(source).toContain("block-sequence");
    expect(source).toContain("leadership-handoff");
    expect(source).toContain("Preview spine");
    expect(source).toContain("Build the report");
    expect(source).toContain("Reader promise");
    expect(source).toContain("Leadership story");
    expect(source).toContain("Proof gate");
    expect(source).toContain("Export artifact");
    expect(source).toContain("Decision story");
    expect(source).toContain("Evidence view");
    expect(source).toContain("Export style");
    expect(source).toContain("Story order");
    expect(source).toContain("Decision recipe");
    expect(source).toContain("Question");
    expect(source).toContain("Visual job");
    expect(source).toContain("Evidence gate");
    expect(source).toContain("Next action");
    expect(source).toContain("Leadership handoff");
    expect(source).toContain("Save the report shape, then exports and shared links carry this trust gate.");
    expect(source).toContain("Output preview updates immediately.");
    expect(source).toContain("Ready for leadership sharing.");
    expect(source).toContain("assertNoCarelessReportCountLabels");
    expect(source).toContain("1 channels");
    expect(source).toContain("document.body.innerText || document.body.textContent || ''");
    expect(source).toContain("assertReportBuilderStoryStrip");
    expect(source).toContain("Report builder story diagnostics");
    expect(source).toContain('contractText.includes("Report trust") || contractText.includes(${JSON.stringify(CUSTOM_REPORT_SECTION_LABELS.report_trust)})');
    expect(source).not.toContain("layoutRect.width >= 800");
    expect(source).not.toContain("controlsRect.width >= 420");
    expect(source).not.toContain("previewRect.width >= 280");
    expect(source).not.toContain("rect.height >= 300");
    expect(source).toContain("report-builder-preset");
    expect(source).toContain("report-builder-chart-mode");
    expect(source).toContain("report-builder-chart-focus");
    expect(source).toContain("report-builder-chart-focus-option");
    expect(source).toContain("report-builder-presentation");
    expect(source).toContain("report-builder-presentation-option");
    expect(source).toContain("selectReportBuilderChartFocus");
    expect(source).toContain("selectReportBuilderPresentation");
    expect(source).toContain("report-builder-framing");
    expect(source).toContain("report-builder-headline");
    expect(source).toContain("report-builder-executive-question");
    expect(source).toContain("assertReportBuilderExecutiveFraming");
    expect(source).toContain("report-builder-tile-controls");
    expect(source).toContain("report-builder-kpi-tile");
    expect(source).toContain("report-builder-trust-tile");
    expect(source).toContain("selectReportBuilderTileSet");
    expect(source).toContain("assertReportBuilderTilePreview");
    expect(source).toContain("CUSTOM_REPORT_KPI_TILE_IDS");
    expect(source).toContain("CUSTOM_REPORT_TRUST_TILE_IDS");
    expect(source).toContain("CUSTOM_REPORT_KPI_TILE_LABELS");
    expect(source).toContain("CUSTOM_REPORT_TRUST_TILE_LABELS");
    expect(source).toContain("CUSTOM_REPORT_SECTION_LABELS");
    expect(source).toContain("CUSTOM_REPORT_SAVED_SECTION_LABELS");
    expect(source).toContain("selectReportBuilderSectionLabels");
    expect(source).toContain("report-builder-section-labels");
    expect(source).toContain("report-builder-section-label");
    expect(source).toContain("report-builder-kpi-tile-label");
    expect(source).toContain("report-builder-trust-tile-label");
    expect(source).toContain("Board evidence scorecard");
    expect(source).toContain("Channel evidence story");
    expect(source).toContain("Audit confidence");
    expect(source).toContain("Next market actions");
    expect(source).toContain("Cost per Engagement");
    expect(source).toContain("Report status");
    expect(source).toContain("Verified reads");
    expect(source).toContain("US market proof report");
    expect(source).toContain("Is the launch evidence strong enough to continue scaling in the United States?");
    expect(source).toContain("us-market-proof-report");
    expect(source).toContain("report-builder-block-order");
    expect(source).toContain("report-builder-block-move-earlier");
    expect(source).toContain("moveReportBuilderBlockEarlier");
    expect(source).toContain("includeReportFraming");
    expect(source).toContain('ensureReportBuilderBlockSelected({ blockId: "report_framing", client });');
    expect(source).toContain('data-chart-recipe=\\"decision-recipe\\"');
    expect(source).toContain("decision-recipe-rail");
    expect(source).toContain("decision-recipe-step");
    expect(source).toContain("decision-recipe-index");
    expect(source).toContain("Decision recipe");
    expect(source).toContain("Question, visual job, evidence gate, and action");
    expect(source).toContain("Report composition");
    expect(source).toContain("composition-ledger");
    expect(source).toContain("composition-row");
    expect(source).toContain('data-composition-row=\\"report-plan\\"');
    expect(source).toContain("Report blocks");
    expect(source).toContain("block-ledger");
    expect(source).toContain("block-row");
    expect(source).toContain('data-report-block-row=\\"recommendations\\"');
    expect(source).toContain("REPORT_EXPORT_MODE_CONTRACTS");
    expect(source).toContain("report-builder-save-template");
    expect(source).toContain("report-builder-save-template-dialog");
    expect(source).toContain("report-builder-template");
    expect(source).toContain("saveReportTemplateFromBuilder");
    expect(source).toContain("!document.querySelector('[data-testid=\"report-builder-save-template-dialog\"][data-open]')");
    expect(source).not.toContain("!document.querySelector('[data-testid=\"report-builder-save-template-name\"]')");
    expect(source).toContain("report-builder-save-campaign-shape");
    expect(source).toContain("saveCampaignReportShapeFromBuilder");
    expect(source).toContain("campaign_reporting_plans");
    expect(source).toContain("Saved to this campaign.");
    expect(source).toContain("report-output-contract");
    expect(source).toContain("report-output-executive-read");
    expect(source).toContain("data-executive-read-state");
    expect(source).toContain("report-output-decision-recipe");
    expect(source).toContain("report-output-decision-recipe-item");
    expect(source).toContain("data-recipe-step");
    expect(source).toContain("Leadership readiness");
    expect(source).toContain("Visual job");
    expect(source).toContain("Evidence gate");
    expect(source).toContain("Next action");
    expect(source).toContain("report-output-readiness-step");
    expect(source).toContain("data-readiness-step");
    expect(source).toContain("Presentation plan");
    expect(source).toContain("proof-room-scale-readiness");
    expect(source).toContain("Proof operations");
    expect(source).toContain("data-proof-readiness-action");
    expect(source).toContain("Ready for leadership sharing");
    expect(source).toContain("No open proof lanes");
    expect(source).toContain("report-executive-cover");
    expect(source).toContain("report-executive-cover-metric");
    expect(source).toContain("data-cover-metric-source");
    expect(source).toContain("data-cover-metric-key");
    expect(source).toContain('coverText.includes("Views") || coverText.includes(${JSON.stringify(CUSTOM_REPORT_KPI_TILE_LABELS.views)})');
    expect(source).toContain('coverText.includes("Engagements") || coverText.includes(${JSON.stringify(CUSTOM_REPORT_KPI_TILE_LABELS.engagements)})');
    expect(source).toContain('coverText.includes("Evidence-backed reads") || coverText.includes(${JSON.stringify(CUSTOM_REPORT_TRUST_TILE_LABELS.evidence_backed_reads)})');
    expect(source).toContain('!coverText.includes("Evidence status")');
    expect(source).toContain("report-executive-cover-visual");
    expect(source).toContain("report-executive-cover-image");
    expect(source).toContain("report-executive-cover-fallback");
    expect(source).toContain("report-executive-cover-fallback-signal");
    expect(source).toContain("Proof visual");
    expect(source).toContain("Built from the report question, evidence state, and selected metrics.");
    expect(source).toContain('fallbackText.includes("Views") || fallbackText.includes(${JSON.stringify(CUSTOM_REPORT_KPI_TILE_LABELS.views)})');
    expect(source).toContain('fallbackText.includes("Engagements") || fallbackText.includes(${JSON.stringify(CUSTOM_REPORT_KPI_TILE_LABELS.engagements)})');
    expect(source).toContain('fallbackText.includes("Evidence-backed reads") || fallbackText.includes(${JSON.stringify(CUSTOM_REPORT_TRUST_TILE_LABELS.evidence_backed_reads)})');
    expect(source).toContain("report-export-ui-proof-room-cover-smoke.png");
    expect(source).toContain("proofRoomCoverScreenshotPath");
    expect(source).toContain("live report proof visual fallback follows proof room presentation");
    expect(source).toContain("live report presentation follows builder controls");
    expect(source).toContain('data-cover-mode") === "proof_room"');
    expect(source).toContain('data-cover-source") === "proof-room"');
    expect(source).toContain('data-cover-mode") === "campaign_visual"');
    expect(source).toContain('data-typography") === "compact"');
    expect(source).toContain('data-report-typography") === "compact"');
    expect(source).toContain("REPORT_CAMPAIGN_VISUAL_TITLE");
    expect(source).toContain("Maison Lumiere New York launch still");
    expect(source).not.toContain("Market launch hero visual");
    expect(source).not.toContain("Global proof campaign visual");
    expect(source).toContain('alt="${REPORT_CAMPAIGN_VISUAL_TITLE}"');
    expect(source).toContain("<figcaption>${REPORT_CAMPAIGN_VISUAL_TITLE}</figcaption>");
    expect(source).toContain("object-fit: contain;");
    expect(source).toContain("padding: 18px 18px 58px;");
    expect(source).toContain('imageStyle?.objectFit === "contain"');
    expect(source).toContain('imageStyle?.paddingBottom === "58px"');
    expect(source).toContain('image?.getAttribute("alt") === ${JSON.stringify(REPORT_CAMPAIGN_VISUAL_TITLE)}');
    expect(source).toContain('img[alt="${REPORT_CAMPAIGN_VISUAL_TITLE}"][data-testid="report-executive-cover-image"]');
    expect(source).not.toContain("Smoke product image");
    expect(source).toContain("assertClientDownloadHasEmbeddedCampaignVisual");
    expect(source).toContain("assertPdfDownloadCarriesProofStory");
    expect(source).toContain("assertPowerPointBodySlidesCarryProofStory");
    expect(source).toContain("assertDownloadTextCarriesCustomReportLabels");
    expect(source).toContain("downloaded report is missing custom KPI label");
    expect(source).toContain("downloaded report is missing custom trust label");
    expect(source).toContain("downloaded report is missing campaign image caption");
    expect(source).toContain("downloaded report still includes legacy trust label");
    expect(source).toContain("downloaded report still says reviewed proof is not reviewed");
    expect(source).toContain("downloaded report still includes internal report plan label");
    expect(source).toContain("renderClientDownloadPreview");
    expect(source).toContain("readPdfTextWithPythonFallback");
    expect(source).toContain("resolvePdfTextPythonCandidates");
    expect(source).toContain("renderDownloadPreviewWithQuickLook");
    expect(source).toContain("renderPdfDownloadPreview");
    expect(source).toContain("report-export-ui-pdf-cover-smoke.png");
    expect(source).toContain("report-export-ui-pptx-cover-smoke.png");
    expect(source).toContain("pdftoppm");
    expect(source).toContain("pdftotext");
    expect(source).toContain("qlmanage");
    expect(source).toContain("unzip");
    expect(source).toContain("ppt/slides/slide*.xml");
    expect(source).toContain("/Subtype /Image");
    expect(source).toContain("ppt/media/image");
    expect(source).toContain("Decision read");
    expect(source).toContain("Evidence trail");
    expect(source).toContain("Next action");
    expect(source).toContain("Trust decision");
    expect(source).toContain("Ready for leadership sharing.");
    const proofStoryArtifactChecks = source.match(
      /const requiredBodyStory = \[[\s\S]*?"Decision read",[\s\S]*?"Evidence trail",[\s\S]*?"Next action",[\s\S]*?"Trust decision",[\s\S]*?"Ready for leadership sharing\.",[\s\S]*?\];/g,
    ) ?? [];
    expect(proofStoryArtifactChecks.length).toBeGreaterThanOrEqual(2);
    expect(source).toContain("Global proof room");
    expect(source).toContain("expectedHeroProofMetric");
    expect(source).toContain("<span>Proof coverage</span>");
    expect(source).toContain("<small>Native analytics screenshots</small>");
    expect(source).toContain("report-export-ui-cover-smoke.png");
    expect(source).toContain("coverScreenshotPath");
    expect(source).toContain("const expectedOutputTitle =");
    expect(source).not.toContain("requiresTemplate");
    expect(source).not.toContain("Boolean(modeContract.requiresTemplate)");
    expect(source).toContain("Exports and shared links follow this saved presentation plan.");
    expect(source).toContain("smokeConfiguredReportShareLink");
    expect(source).toContain("smokeSharedReportLeadershipGate");
    expect(source).toContain("withFreshSharedReportPage");
    expect(source).toContain("viewerClient");
    expect(source).toContain("sharedReportClient");
    expect(source).toContain("debugPort");
    expect(source).toContain("skipBrandReview: true");
    expect(source).toContain("verifyBrandReportEvidence");
    expect(source).toContain("report-share-button");
    expect(source).toContain("report-share-trust-gate");
    expect(source).toContain("report-share-trust-decision");
    expect(source).toContain("expectedTrustDecision");
    expect(source).toContain("expectedTrustState");
    expect(source).toContain("Shared links show this same trust decision before any leadership KPIs.");
    expect(source).toContain("report-share-url");
    expect(source).toContain("Shared campaign report");
    expect(source).toContain("sharedReportScreenshotPath");
    expect(source).toContain("sharedReportHoldScreenshotPath");
    expect(source).toContain("report-export-ui-shared-report-smoke.png");
    expect(source).toContain("report-export-ui-shared-report-hold-smoke.png");
    expect(source).toContain("recommendation-memo");
    expect(source).toContain("Recommended move");
    expect(source).toContain("Supporting evidence");
    expect(source).toContain("shared-report-executive-cover");
    expect(source).toContain("shared-report-executive-cover-metric");
    expect(source).toContain('const text = document.body.textContent || "";');
    expect(source).toMatch(
      /const configuredCoverExpression = `\(\(\) => \{\s+const text = document\.body\.textContent \|\| "";/,
    );
    expect(source).toContain("data-cover-metric-source");
    expect(source).toContain("data-cover-metric-key");
    expect(source).toContain("shared-report-executive-cover-visual");
    expect(source).toContain("shared-report-executive-cover-image");
    expect(source).toContain("shared-report-leadership-gate");
    expect(source).toContain("shared-report-leadership-next-action");
    expect(source).toContain("shared-report-proof-basis");
    expect(source).toContain("shared-report-proof-basis-item");
    expect(source).toContain('data-proof-basis-key") === "included"');
    expect(source).toContain('data-proof-basis-key") === "needs-review"');
    expect(source).toContain('data-proof-basis-key") === "corrections"');
    expect(source).toContain('data-proof-basis-key") === "missing-proof"');
    expect(source).toContain("shared-report-leadership-hold-panel");
    expect(source).toContain("shared-report-hold-next-action");
    expect(source).toContain("Performance detail held for evidence review");
    expect(source).toContain('data-cover-source") === "campaign-image"');
    expect(source).toContain('data-leadership-state") === expectedState');
    expect(source).toContain('coverMetrics.every((metric) => metric.getAttribute("data-cover-metric-source") === "trust")');
    expect(source).toContain("shared-report-hold-proof-item");
    expect(source).toContain('!document.querySelector(\'[data-testid="shared-report-kpi-card"]\')');
    expect(source).toContain('!document.querySelector(\'[data-testid="shared-report-recommendations"]\')');
    expect(source).toContain('!document.querySelector(\'[data-testid="shared-report-selected-metric-value"]\')');
    expect(source).toContain('!text.includes("Creator Performance")');
    expect(source).toContain('!text.includes("No chart data yet")');
    expect(source).toContain('coverText.includes("Proof coverage")');
    expect(source).toContain('coverText.includes("Qualified reach")');
    expect(source).not.toMatch(/&&\s+coverText\.includes\("Evidence status"\)/);
    expect(source).toContain('expectedState: "hold"');
    expect(source).toContain('expectedState: "ready"');
    expect(source).toContain("Leadership hold");
    expect(source).toContain('data-leadership-state") === "ready"');
    expect(source).toContain("Leadership-ready");
    expect(source).toContain("Keep in proof room until evidence is reviewed.");
    expect(source).toContain("expectedNextAction");
    expect(source).toContain("Review 1 submitted proof read before sharing.");
    expect(source).toContain("configured shared campaign report leadership hold");
    expect(source).toContain("configured shared campaign report executive cover");
    expect(source).toContain("configured shared campaign report leadership gate");
    expect(source).toContain("configured shared campaign report story snapshot");
    expect(source).toContain("shared-report-story-snapshot-callout");
    expect(source).toContain("report-chart-layout-story");
    expect(source).toContain("report-story-decision-step");
    expect(source).toContain("data-decision-step");
    expect(source).not.toContain("report-story-decision-card");
    expect(source).toContain("Primary report story");
    expect(source).toContain("proof_audit");
    expect(source).toContain("Custom report");
    expect(source).toContain("Global proof leadership smoke");
    expect(source).toContain("Report composition");
    expect(source).toContain("UI-triggered report export artifact still used the default campaign report title.");
    expect(source).toContain("Saved report template did not persist the custom report title.");
    expect(source).toContain("Campaign report plan did not persist the custom executive question.");
    expect(source).toContain("Saved report template did not persist the custom section labels.");
    expect(source).toContain("Campaign report plan did not persist the custom section labels.");
    expect(source).toContain("data-report-cover-mode=\\\"campaign_visual\\\"");
    expect(source).toContain("data-report-typography=\\\"compact\\\"");
    expect(source).toContain("data-report-density=\\\"compact\\\"");
    expect(source).toContain("Executive question");
    expect(source).toContain("\"Report plan\"");
    expect(source).toContain("\"Team template\"");
    expect(source).toContain("TEMPLATE_NAME_PREFIX");
    expect(source).not.toContain('"Team template",\n      "Executive question"');
    expect(source).toContain("artifactAbsentChecks");
    expect(source).toContain("Unexpected ${label} in UI-triggered report export artifact.");
    expect(source).toContain("data-testid=\"report-export-menu\"");
    expect(source).toContain("Chart layout");
    expect(source).toContain("Timeline readout");
    expect(source).toContain("data-report-chart-mode=\\\"trend\\\"");
    expect(source).toContain("report-story--trend");
    expect(source).toContain("data-report-chart-mode=\\\"comparison\\\"");
    expect(source).toContain("data-comparison-focus=\\\"cpe\\\"");
    expect(source).toContain("report-story--comparison");
    expect(source).toContain("Creator comparison by Efficiency signal");
    expect(source).toContain("Sorted by Efficiency signal. Lower CPE ranks first.");
    expect(source).toContain("data-chart-metric");
    expect(source).toContain("data-report-chart-mode=\\\"proof\\\"");
    expect(source).toContain("report-story--proof");
    expect(source).toContain("Proof source readiness");
    expect(source).toContain("Leadership impact");
    expect(source).toContain("What is included in leadership totals");
    expect(source).toContain('data-impact-key="included"');
    expect(source).toContain('data-impact-key="needs-review"');
    expect(source).toContain('data-impact-key="corrections"');
    expect(source).toContain('data-impact-key="missing-proof"');
    expect(source).toContain("data-leadership-handoff-state=\\\"ready\\\"");
    expect(source).toContain("Leadership handoff");
    expect(source).toContain("Share with leadership");
    expect(source).toContain("Proof basis");
    expect(source).toContain('data-proof-basis-key="included"');
    expect(source).toContain('data-proof-basis-key="needs-review"');
    expect(source).toContain('data-proof-basis-key="corrections"');
    expect(source).toContain('data-proof-basis-key="missing-proof"');
    expect(source).toContain("Primary report story");
    expect(source).toContain("Lead metric");
    expect(source).toContain("Single read. Snapshot recipe selected automatically.");
    expect(source).toContain("Snapshot read");
    expect(source).toContain("One verified read; use a snapshot until there is enough history for a trend.");
    expect(source).toContain("data-chart-recipe=\\\"single-read-ledger\\\"");
    expect(source).toContain("decision-list");
    expect(source).toContain("Creator-level evidence");
    expect(source).toContain("Lead with movement over time, pacing, and the final decision signal.");
    expect(source).toContain("exportedReportModes");
    expect(source).toContain("renderReportExportArtifact");
    expect(source).toContain("visualScreenshotPath");
    expect(source).toContain("report-export-ui-trend-artifact-smoke.png");
    expect(source).toContain("report-export-ui-comparison-artifact-smoke.png");
    expect(source).toContain("report-export-ui-proof-artifact-smoke.png");
    expect(source).toContain("data:text/html;charset=utf-8,");
    expect(source).toContain("getBoundingClientRect");
    expect(source).toContain("captureScreenshot(client, modeContract.visualScreenshotPath");
    expect(source).toContain("excludedJobIds.add(job.id)");
    expect(source).toContain("validateReportExportUiSmoke({ job, artifactText, consoleErrors, modeContract })");
    expect(source).toContain("report_export_jobs");
    expect(source).toContain("report-exports");
    expect(source).toContain("isEnabledHtmlReportExportItem");
    expect(source).toContain('!item.hasAttribute("data-disabled")');
    expect(source).toContain('item.getAttribute("aria-disabled") !== "true"');
    expect(source).toContain("enabled HTML report export menu item");
    expect(source).toContain("Browser.setDownloadBehavior");
    expect(source).toContain("smokeClientDownloadExport");
    expect(source).toContain("PDF report");
    expect(source).toContain("PowerPoint deck");
    expect(source).toContain("waitForDownloadedReport");
    expect(source).toContain(".pdf");
    expect(source).toContain(".pptx");
    expect(source).toContain("clientDownloadExports");
    expect(source).toContain("REPORT_EXPORT_STALE_SERVICE_ERROR");
    expect(source).toContain("assertNoVisibleStaleReportExportServiceError");
    expect(source).toContain("Report blocks");
    expect(source).toContain("Creator Performance");
    expect(source).toContain("Data source");
    expect(source).toContain("Brand-reviewed proof");
    expect(source).toContain("Creator evidence reviewed by brand");
    expect(source).not.toContain('"How metrics entered PopsDrops"');
    expect(source).toContain("Proof coverage: 1/1 / Brand-reviewed proof");
    expect(source).toContain("HTML report artifact still says reviewed proof is not reviewed.");
    expect(source).toContain("Report window");
    expect(source).toContain("report-hero--visual-led");
    expect(source).toContain("metric-callout");
    expect(source).toContain("Leadership watchpoint");
    expect(source).toContain("UI-triggered report export artifact still uses boxed metric-card styling.");
    expect(source).toContain("--value: #475569;");
    expect(source).toContain("font-size: 17px;");
    expect(source).toContain("cleanupApplicationFlowSmokeData");
    expect(sharedReportSource).toContain("key: card.key");
    expect(sharedReportSource).toContain('key: "evidence_backed_reads"');
    expect(sharedReportSource).toContain('key: "verified_reads"');
    expect(sharedReportSource).toContain('key: "data_window"');
    expect(sharedReportSource).toContain('key: "report_status"');
    expect(sharedReportSource).toContain('key: "data_source"');
  });
});
