-- ============================================================
-- 015_seed_brief_translations.sql
-- Pre-populate brief translations for Haneul Cosmetics campaigns.
-- In production, these are generated by Gemini on publish.
-- ============================================================

-- Glass Skin Ritual — Central Asia Launch (c0000000-0000-0000-0000-000000000007)
UPDATE campaigns SET brief_translated = '{
  "ru": {
    "description": "Представьте набор Haneul Glass Skin вашей аудитории. Покажите вашу настоящую утреннюю или вечернюю рутину ухода за кожей, используя все 3 продукта: тонер, сыворотку и крем-барьер для увлажнения. Мы хотим увидеть аутентичный контент «собирайся со мной», который выглядит естественно и близко — не обзор продукта, а момент из жизни.",
    "requirements": "Используйте все 3 продукта из набора Glass Skin по порядку (тонер → сыворотка → крем).\nПокажите текстуру кожи до/после, если вам комфортно.\nУпомяните @haneulcosmetics и #GlassSkinRitual.\nДобавьте ссылку в био или свайп-ап, где доступно.",
    "dos": "Снимайте при естественном свете — золотой час, свет из окна или зеркало в ванной.\nПоделитесь честным первым впечатлением.\nГоворите на родном языке (казахский, русский или оба).\nПокажите упаковку продукта и текстуру крупным планом.",
    "donts": "Никаких фильтров, изменяющих текстуру кожи.\nНикаких продуктов конкурентов в кадре.\nНикаких медицинских или дерматологических заявлений.\nНикакой озвучки с ИИ — мы хотим услышать ваш настоящий голос."
  },
  "kk": {
    "description": "Haneul Glass Skin жинағын аудиторияңызға таныстырыңыз. Барлық 3 өнімді қолдана отырып, шынайы таңғы немесе кешкі тері күтімі тәртібіңізді көрсетіңіз: тонер, сарысу және ылғалдандырғыш крем. Біз «менімен бірге дайындал» форматындағы табиғи және шынайы контент алғымыз келеді — өнімге шолу емес, өмірден алынған сәт.",
    "requirements": "Glass Skin жинағындағы барлық 3 өнімді ретімен қолданыңыз (тонер → сарысу → крем).\nМүмкіндігінше тері текстурасын бұрын/кейін көрсетіңіз.\n@haneulcosmetics және #GlassSkinRitual деп белгілеңіз.\nБио-да немесе свайп-ап мүмкіндігі бар жерде сілтемені қосыңыз.",
    "dos": "Табиғи жарықта түсіріңіз — алтын сағат, терезе жарығы немесе ванна бөлмесі айнасы.\nШынайы алғашқы әсеріңізбен бөлісіңіз.\nАна тіліңізде сөйлеңіз (қазақша, орысша немесе екеуінде де).\nӨнімнің қаптамасын және текстурасын жақын көріністе көрсетіңіз.",
    "donts": "Тері текстурасын өзгертетін сүзгілер болмасын.\nКадрда бәсекелес өнімдер болмасын.\nМедициналық немесе дерматологиялық мәлімдемелер жасамаңыз.\nЖасанды интеллект дауысын пайдаланбаңыз — біз сіздің шынайы дауысыңызды естігіміз келеді."
  },
  "uz": {
    "description": "Haneul Glass Skin toʻplamini auditoriyangizga taqdim eting. Barcha 3 mahsulotni — toner, serum va namlovchi kremni ishlatib, haqiqiy ertalabki yoki kechki parvarish tartibingizni koʻrsating. Biz tabiiy va samimiy «men bilan tayyor boʻling» kontentini xohlaymiz — mahsulot sharhi emas, balki hayotdan olingan lahza.",
    "requirements": "Glass Skin toʻplamidagi barcha 3 mahsulotni tartib bilan ishlating (toner → serum → krem).\nImkon boʻlsa, teri teksturasini oldin/keyin koʻrsating.\n@haneulcosmetics va #GlassSkinRitual deb belgilang.\nBio yoki svayp-ap imkoniyati bor joyda havolani qoʻshing.",
    "dos": "Tabiiy yorugʻlikda suring — oltin soat, deraza yorugʻligi yoki vannaxona oynasi.\nHaqiqiy birinchi taassurotingizni baham koʻring.\nOna tilingizda gaplashing.\nMahsulot qadogʻi va teksturasini yaqindan koʻrsating.",
    "donts": "Teri teksturasini oʻzgartiruvchi filtrlar boʻlmasin.\nKadrdagi raqobatchi mahsulotlar boʻlmasin.\nTibbiy yoki dermatologik daʼvolar qilmang.\nSunʼiy intellekt ovozidan foydalanmang — biz sizning haqiqiy ovozingizni eshitmoqchimiz."
  }
}'::jsonb
WHERE id = 'c0000000-0000-0000-0000-000000000007';

-- Haneul × Almaty — City Skin Diaries (c0000000-0000-0000-0000-000000000008)
UPDATE campaigns SET brief_translated = '{
  "ru": {
    "description": "Покажите ваш день в Алматы, органично включив крем-барьер Haneul Moisture Barrier Cream в вашу рутину. Мы хотим увидеть город вашими глазами — утренний кофе, горы, улицы — с одним моментом, где продукт появляется естественно. Думайте: лайфстайл-контент с элементом ухода за кожей, а не реклама продукта.",
    "requirements": "Покажите крем Moisture Barrier Cream хотя бы один раз в видео.\nОтметьте @haneulcosmetics и #CityGlow.\nПодпись на вашем языке — перевод не нужен.",
    "dos": "Покажите настоящий Алматы — места, куда вы реально ходите.\nДержите стиль откровенным и кинематографичным.\nВаш голос, ваш стиль.",
    "donts": "Никаких студийных съёмок.\nНикакого навязчивого рекламного текста.\nНикаких кадров только с продуктом без лайфстайл-контекста."
  },
  "kk": {
    "description": "Алматыдағы күніңізді Haneul Moisture Barrier Cream кремін күнделікті тәртібіңізге қоса отырып көрсетіңіз. Біз қаланы сіздің көзіңіз арқылы көргіміз келеді — таңғы кофе, таулар, көшелер — өнім табиғи түрде пайда болатын бір сәтпен. Ойлаңыз: тері күтімі элементі бар лайфстайл-контент, өнім жарнамасы емес.",
    "requirements": "Moisture Barrier Cream кремін бейнеде кемінде бір рет көрсетіңіз.\n@haneulcosmetics және #CityGlow деп белгілеңіз.\nЖазба тіліңізде — аударма қажет емес.",
    "dos": "Шынайы Алматыны көрсетіңіз — сіз шын мәнінде баратын жерлерді.\nОны шынайы және кинематографиялық ұстаңыз.\nСіздің дауысыңыз, сіздің стиліңіз.",
    "donts": "Студиялық түсірілімдер болмасын.\nНавязчивый жарнама мәтіні болмасын.\nЛайфстайл контекстісіз тек өнім кадрлары болмасын."
  }
}'::jsonb
WHERE id = 'c0000000-0000-0000-0000-000000000008';
