export const strings: Record<string, Record<string, string>> = {
  common: {
    "app.name": "PopsDrops",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.done": "Done",
    "action.next": "Next",
    "action.back": "Back",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.apply": "Apply",
    "action.search": "Search",
    "action.signOut": "Sign Out",
    "action.connect": "Connect",
    "action.editProfile": "Edit Profile",
    "loading": "Loading\u2026",
    "error.generic": "Something went wrong",
    "error.network": "Check your connection",
  },
  preferences: {
    "preferences.title": "Preferences",
    "preferences.appearanceTitle": "Appearance",
    "preferences.appearanceDetail":
      "Match your device or choose a dedicated light or dark interface.",
    "preferences.languageTitle": "Language",
    "preferences.languageDetail":
      "Choose the interface language for this device. English is always one tap away.",
    "preferences.languageSync":
      "Your selection also syncs to your PopsDrops profile when you are signed in.",
    "preferences.languageCurrent": "Current language",
    "preferences.languageSearch": "Search languages",
    "preferences.languagePinned": "Pinned",
    "preferences.languageSuggested": "Suggested",
    "preferences.languageAll": "All languages",
    "preferences.languageLoading": "Updating language…",
    "preferences.themeSystem": "System",
    "preferences.themeLight": "Light",
    "preferences.themeDark": "Dark",
    "preferences.themeCurrent": "Current appearance",
  },
  tabs: {
    "tab.home": "Home",
    "tab.discover": "Discover",
    "tab.campaigns": "Campaigns",
    "tab.earnings": "Earnings",
    "tab.profile": "Profile",
  },
  auth: {
    "auth.welcome": "Welcome to PopsDrops",
    "auth.welcomeBack": "Welcome back",
    "auth.subtitle": "The global creator marketplace",
    "auth.signInGoogle": "Continue with Google",
    "auth.signInEmail": "Continue with email",
    "auth.emailPlaceholder": "your@email.com",
    "auth.sendLink": "Send sign-in link",
    "auth.checkEmail": "Check your email",
    "auth.checkEmailDetail": "We sent a sign-in link to {email}",
    "auth.orDivider": "or",
    "auth.completingSignIn": "Completing sign-in",
    "auth.signInFailed": "We couldn’t finish your sign-in",
    "auth.signInFailedDetail":
      "The mobile sign-in link is invalid or expired. Return to login and request a fresh link.",
    "auth.returnToLogin": "Return to login",
  },
  access: {
    "access.creatorOnlyTitle": "This app is for creator accounts",
    "access.creatorOnlyDetail":
      "Brand and admin work stays on the web platform. Sign in with an approved creator account to continue in the mobile app.",
    "access.invitationRequiredTitle": "Invitation required",
    "access.invitationRequiredDetail":
      "PopsDrops is an invite-only platform for vetted creators. If you\u2019ve been invited, check your email for a sign-in link. Otherwise, ask the brand or team that referred you to send an invitation.",
    "access.accountUnavailableTitle": "Your account is not available on mobile",
    "access.accountUnavailableDetail":
      "We could not open the creator app for this account. Try signing in again or contact PopsDrops support if the issue persists.",
  },
  waitlist: {
    "waitlist.title": "Request access",
    "waitlist.subtitle":
      "PopsDrops is invite-only. Tell us about yourself and we\u2019ll reach out if there\u2019s a fit.",
    "waitlist.nameLabel": "Full name",
    "waitlist.namePlaceholder": "Your name",
    "waitlist.emailLabel": "Email",
    "waitlist.platformLabel": "Primary platform",
    "waitlist.socialUrlLabel": "Profile link",
    "waitlist.socialUrlPlaceholder": "https://tiktok.com/@yourhandle",
    "waitlist.followersLabel": "Followers",
    "waitlist.submit": "Request access",
    "waitlist.signOutInstead": "Sign out instead",
    "waitlist.submittedTitle": "You\u2019re on the list",
    "waitlist.submittedDetail":
      "We review every request personally. If your profile is a fit for upcoming campaigns, we\u2019ll send you an invitation.",
  },
  home: {
    "home.greeting": "Good {timeOfDay}",
    "home.greetingName": "Good {timeOfDay}, {name}",
    "home.morning": "morning",
    "home.afternoon": "afternoon",
    "home.evening": "evening",
    "home.subtitle": "Here\u2019s your overview",
    "home.statusSetup": "Let\u2019s get you set up",
    "home.statusClear": "You\u2019re all clear",
    "home.actionRequired": "Action Required",
    "home.newMatches": "Campaigns For You",
    "home.activeCampaigns": "Active",
    "home.pendingApplications": "Pending",
    "home.counterOffers": "Offers",
    "home.rating": "Rating",
    "home.topMatches": "Recommended",
    "home.seeAll": "See All",
    "home.recentActivity": "Recent Activity",
    "home.empty": "Your creator journey starts here",
    "home.emptyDetail":
      "Build your profile and we\u2019ll match you with campaigns from global brands",
    "home.completeProfile": "Complete Profile",
    "home.profileComplete": "{percent}% complete",
    "home.finishProfile": "Finish your profile to get discovered",
    "home.noTasks": "No tasks right now",
    "home.noTasksDetail": "New opportunities will appear here",
    "home.exploreCampaigns": "Explore Campaigns",
    "home.daysLeft": "{count}d left",
    "home.dueSoon": "Content due in {days} days",
    "home.dueToday": "Content due today",
    "home.counterOffer": "Counter offer: {rate}",
    "home.counterDetail": "You proposed {rate}",
  },
  campaignDetail: {
    "campaignDetail.title": "Campaign",
    "campaignDetail.budget": "Budget",
    "campaignDetail.deadline": "Application Deadline",
    "campaignDetail.platforms": "Platforms",
    "campaignDetail.niches": "Focus Areas",
    "campaignDetail.markets": "Target Markets",
    "campaignDetail.apply": "Apply to Campaign",
    "campaignDetail.applied": "Application Submitted",
    "campaignDetail.spotsOpen": "Accepting applications",
    "campaignDetail.deadlinePassed": "Deadline passed",
    "campaignDetail.budgetOnRequest": "Budget on request",
  },
  discover: {
    "discover.title": "Discover",
    "discover.forYou": "For You",
    "discover.browseAll": "Browse All",
    "discover.search": "Search campaigns\u2026",
    "discover.empty": "No campaigns match your filters",
    "discover.emptyDetail":
      "Try broadening your search or check back tomorrow",
    "discover.recommended": "Recommended",
    "discover.matchScore": "{score}% match",
    "discover.spotsLeft": "{count} spots left",
    "discover.daysLeft": "{count} days left",
    "discover.perPost": "per post",
    "discover.budgetOnRequest": "Budget on request",
    "discover.appliedPending": "Applied",
    "discover.counterOffer": "Counter offer",
    "discover.open": "Open",
    "discover.deadlineUnknown": "Deadline TBD",
    "discover.filters": "Filters",
    "discover.sortBy": "Sort by",
    "discover.sortRecommended": "Recommended",
    "discover.sortNewest": "Newest",
    "discover.sortHighestPaying": "Highest paying",
    "discover.sortDeadline": "Deadline soonest",
    "discover.clearFilters": "Clear all",
    "discover.applyFilters": "Apply filters",
    "discover.nicheFilter": "Niche",
    "discover.marketFilter": "Market",
    "discover.budgetFilter": "Budget",
    "discover.budgetAny": "Any budget",
    "discover.budgetUnder500": "Under $500",
    "discover.budget500to1k": "$500\u2013$1,000",
    "discover.budget1kPlus": "$1,000+",
    "discover.activeFilters": "{count} active",
    "discover.matchNiche": "Matches your niche",
    "discover.matchPlatform": "Your platform",
    "discover.matchMarket": "Your market",
    "discover.deliverables": "{count} deliverables",
  },
  campaigns: {
    "campaigns.title": "My Campaigns",
    "campaigns.active": "Active",
    "campaigns.completed": "Completed",
    "campaigns.applications": "Applications",
    "campaigns.empty": "No active campaigns",
    "campaigns.emptyDetail":
      "Browse opportunities to find your first campaign",
    "campaigns.browse": "Browse Campaigns",
    "campaigns.emptyCompleted": "No completed campaigns yet",
    "campaigns.emptyCompletedDetail":
      "Completed work will appear here after your first finished campaign",
    "campaigns.emptyApplications": "No applications yet",
    "campaigns.emptyApplicationsDetail":
      "Apply to campaigns in Discover to start building your pipeline",
    "campaigns.status.pending": "Pending",
    "campaigns.status.counterOffer": "Counter Offer",
    "campaigns.status.accepted": "Accepted",
    "campaigns.status.rejected": "Rejected",
    "campaigns.status.withdrawn": "Withdrawn",
    "campaigns.due": "Due {date}",
    "campaigns.completedOn": "Completed {date}",
    "campaigns.proposedRate": "Proposed {rate}",
    "campaigns.counterRate": "Counter {rate}",
    "campaigns.withdraw": "Withdraw",
    "campaigns.withdrawTitle": "Withdraw Application",
    "campaigns.withdrawConfirm":
      "Are you sure you want to withdraw your application for {title}? This cannot be undone.",
  },
  profile: {
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.editBasicsTitle": "Edit Profile Basics",
    "profile.fullName": "Full Name",
    "profile.bio": "Bio",
    "profile.primaryMarket": "Primary Market",
    "profile.languages": "Languages",
    "profile.basicsSaved": "Profile updated",
    "profile.basicsError": "We couldn’t save your profile changes",
    "profile.emptyBio": "Add a short introduction so brands know your point of view.",
    "profile.noLanguages": "Select the languages you can work in",
    "profile.noMarket": "Set your primary market",
    "profile.manageOnWeb": "Manage on web",
    "profile.email": "Email",
    "profile.notSet": "Not set",
    "profile.noNiches": "No niches yet",
    "profile.noPlatforms": "No connected platforms yet",
    "profile.mediaKit": "Media Kit",
    "profile.socialAccounts": "Social Accounts",
    "profile.rateCard": "Rate Card",
    "profile.noRates": "No rates set yet",
    "profile.niches": "Niches",
    "profile.completeness": "Profile Completeness",
    "profile.followers": "{count} followers",
    "profile.connected": "Connected",
    "profile.notConnected": "Not connected",
    "profile.rating": "Rating",
    "profile.campaigns": "Campaigns",
    "profile.response": "Response",
    "profile.preferences": "Preferences",
    "profile.preferencesDetail": "Appearance and language",
    "profile.tierNew": "New Creator",
    "profile.tierRising": "Rising Creator",
    "profile.tierEstablished": "Established Creator",
    "profile.tierTop": "Top Creator",
    "profile.completenessGuide": "Complete your profile to get discovered",
    "profile.stepBio": "Add a bio",
    "profile.stepSocial": "Connect a social account",
    "profile.stepSocial2": "Connect a second account",
    "profile.stepNiches": "Select your niches",
    "profile.stepRateCard": "Set your rates",
    "profile.stepMarkets": "Add target markets",
    "profile.stepLanguages": "Set your languages",
    "profile.stepPrimaryMarket": "Set your primary market",
    "profile.stepComplete": "Profile complete",
  },
  niches: {
    "niche.beauty": "Beauty & Skincare",
    "niche.fashion": "Fashion & Apparel",
    "niche.food": "Food & Drink",
    "niche.travel": "Travel",
    "niche.tech": "Tech & Gaming",
    "niche.fitness": "Fitness",
    "niche.gaming": "Gaming",
    "niche.lifestyle": "Lifestyle",
    "niche.education": "Education",
    "niche.entertainment": "Entertainment",
    "niche.parenting": "Parenting",
    "niche.automotive": "Automotive",
    "niche.home": "Home & Decor",
    "niche.health": "Health & Wellness",
    "niche.finance": "Finance",
  },
  apply: {
    "apply.title": "Apply to Campaign",
    "apply.rateLabel": "Your Rate",
    "apply.rateRequired": "Enter a rate of at least $1",
    "apply.pitchLabel": "Your Pitch",
    "apply.pitchPlaceholder":
      "Tell the brand why you\u2019re the right creator for this campaign\u2026",
    "apply.pitchRequired": "Pitch must be at least 10 characters",
    "apply.budgetHint": "Campaign budget: {budget}",
    "apply.submit": "Submit Application",
  },
  campaignDetailExtra: {
    "campaignDetail.counterOffer": "Counter Offer",
    "campaignDetail.yourRate": "Your rate",
    "campaignDetail.brandOffer": "Brand offer",
    "campaignDetail.accept": "Accept Offer",
    "campaignDetail.decline": "Decline",
  },
  room: {
    "room.brief": "Brief",
    "room.tasks": "Tasks",
    "room.submit": "Submit",
    "room.chat": "Chat",
    "room.description": "Description",
    "room.requirements": "Requirements",
    "room.dos": "Do\u2019s",
    "room.donts": "Don\u2019ts",
    "room.deliverables": "Deliverables",
    "room.timeline": "Timeline",
    "room.contentDue": "Content due",
    "room.postingStart": "Posting starts",
    "room.postingEnd": "Posting ends",
    "room.maxRevisions": "Max revisions",
    "room.noDeliverables": "No deliverables defined yet",
    "room.status.not_started": "Not started",
    "room.status.submitted": "Submitted",
    "room.status.approved": "Approved",
    "room.status.revision_requested": "Revision requested",
    "room.status.published": "Published",
    "room.currentStatus": "Current Status",
    "room.submitContent": "Submit Content",
    "room.submitRevision": "Submit Revision",
    "room.contentUrl": "Content URL",
    "room.caption": "Caption",
    "room.captionPlaceholder": "Optional caption for your content\u2026",
    "room.revisionFeedback": "Brand Feedback",
    "room.revisionCount": "Revision {current} of {max}",
    "room.publishContent": "Mark as Published",
    "room.publishDescription":
      "Paste the live URL where your content has been published.",
    "room.markPublished": "Mark Published",
    "room.contentPublished": "Content Published",
    "room.waitingReview": "Waiting for Review",
    "room.waitingReviewDetail":
      "The brand will review your submission and approve or request changes.",
    "room.noMessages": "No messages yet",
    "room.messagePlaceholder": "Type a message\u2026",
  },
  earnings: {
    "earnings.title": "Earnings",
    "earnings.totalEarned": "Total Earned",
    "earnings.thisMonth": "This Month",
    "earnings.pending": "{amount} pending payment",
    "earnings.breakdown": "Campaign Breakdown",
    "earnings.empty": "No earnings yet",
    "earnings.emptyDetail":
      "Earnings from completed campaigns will appear here",
    "earnings.status.pending": "Pending",
    "earnings.status.invoiced": "Invoiced",
    "earnings.status.paid": "Paid",
  },
  notifications: {
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all read",
    "notifications.empty": "No notifications",
    "notifications.emptyDetail":
      "Updates about your campaigns will appear here",
  },
  editNiches: {
    "editNiches.title": "Edit Niches",
    "editNiches.subtitle": "{count}/5 selected",
  },
  editMarkets: {
    "editMarkets.title": "Target Markets",
  },
  editSocials: {
    "editSocials.title": "Social Accounts",
    "editSocials.urlPlaceholder": "Profile URL",
    "editSocials.handlePlaceholder": "@handle",
    "editSocials.followersPlaceholder": "Followers",
  },
  editRates: {
    "editRates.title": "Rate Card",
    "editRates.subtitle":
      "Set your rates per platform and content format. Brands see these when reviewing your profile.",
  },
};
