export const strings: Record<string, Record<string, string>> = {
  common: {
    "app.name": "PopsDrops",
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.done": "Done",
    "action.next": "Next",
    "action.back": "Back",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.apply": "Apply",
    "action.signOut": "Sign Out",
    "action.connect": "Connect",
    "loading": "Loading\u2026",
    "error.generic": "Something went wrong",
    "error.network": "Check your connection",
  },
  tabs: {
    "tab.home": "Home",
    "tab.discover": "Discover",
    "tab.campaigns": "Campaigns",
    "tab.profile": "Profile",
  },
  auth: {
    "auth.welcome": "Welcome to PopsDrops",
    "auth.welcomeBack": "Welcome back",
    "auth.subtitle": "The global creator marketplace",
    "auth.signInGoogle": "Continue with Google",
    "auth.signInEmail": "Continue with email",
    "auth.emailPlaceholder": "your@email.com",
    "auth.sendLink": "Send magic link",
    "auth.checkEmail": "Check your email",
    "auth.checkEmailDetail": "We sent a sign-in link to {email}",
    "auth.orDivider": "or",
  },
  home: {
    "home.greeting": "Good {timeOfDay}",
    "home.greetingName": "Good {timeOfDay}, {name}",
    "home.morning": "morning",
    "home.afternoon": "afternoon",
    "home.evening": "evening",
    "home.statusSetup": "Let\u2019s get you set up",
    "home.statusClear": "You have no pending tasks",
    "home.actionRequired": "Action Required",
    "home.newMatches": "Campaigns For You",
    "home.recentActivity": "Recent Activity",
    "home.empty": "Your creator journey starts here",
    "home.emptyDetail":
      "Build your profile and we\u2019ll match you with campaigns from global brands",
    "home.completeProfile": "Complete Profile",
  },
  discover: {
    "discover.title": "Discover",
    "discover.forYou": "For You",
    "discover.browseAll": "Browse All",
    "discover.search": "Search campaigns\u2026",
    "discover.empty": "No campaigns match your filters",
    "discover.emptyDetail":
      "Try broadening your search or check back tomorrow",
    "discover.matchScore": "{score}% match",
    "discover.spotsLeft": "{count} spots left",
    "discover.daysLeft": "{count} days left",
    "discover.perPost": "per post",
  },
  campaigns: {
    "campaigns.title": "My Campaigns",
    "campaigns.active": "Active",
    "campaigns.completed": "Completed",
    "campaigns.applications": "Applications",
    "campaigns.empty": "No active campaigns",
    "campaigns.emptyDetail":
      "Browse opportunities to find your first campaign",
    "campaigns.browse": "Browse Campaigns",
  },
  profile: {
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.mediaKit": "Media Kit",
    "profile.socialAccounts": "Social Accounts",
    "profile.rateCard": "Rate Card",
    "profile.noRates": "No rates set yet",
    "profile.niches": "Niches",
    "profile.completeness": "Profile Completeness",
    "profile.followers": "{count} followers",
    "profile.connected": "Connected",
    "profile.notConnected": "Not connected",
    "profile.rating": "Rating",
    "profile.campaigns": "Campaigns",
    "profile.response": "Response",
    "profile.tierNew": "New Creator",
    "profile.tierRising": "Rising Creator",
    "profile.tierEstablished": "Established Creator",
    "profile.tierTop": "Top Creator",
  },
  niches: {
    "niche.beauty": "Beauty & Skincare",
    "niche.fashion": "Fashion & Apparel",
    "niche.food": "Food & Drink",
    "niche.travel": "Travel",
    "niche.tech": "Tech & Gaming",
    "niche.fitness": "Fitness",
    "niche.gaming": "Gaming",
    "niche.lifestyle": "Lifestyle",
    "niche.education": "Education",
    "niche.entertainment": "Entertainment",
    "niche.parenting": "Parenting",
    "niche.automotive": "Automotive",
    "niche.home": "Home & Decor",
    "niche.health": "Health & Wellness",
    "niche.finance": "Finance",
  },
};
